# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookFinder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookFinder
    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa'
    pod 'SnapKit', '~> 5.6.0'
    pod 'Then'
    pod 'Acorn'

  target 'BookFinderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BookFinderUITests' do
    # Pods for testing
  end

end
